-- OAUTH IDENTITY BINDING (module §5.5 v1.137, 2026-09-19). Two empty tables
-- that decide which provider ACCOUNT may sign in as which email address.
--
-- WHY. Until now both OAuth doors believed the address the provider reported
-- and keyed users.email on it. For Microsoft that address is Graph `mail`,
-- which the admin of whatever Entra tenant the account lives in can PATCH to
-- anything, and under MICROSOFT_TENANT_ID=common anyone can bring their own
-- tenant (the published nOAuth forgery). oauth_identities records the
-- provider-immutable subject (google `sub`; microsoft `tid:oid` from the ID
-- TOKEN) that has PROVED an address, so the reported email is never believed
-- on its own again. oauth_confirmations holds a sign-in that is HELD while a
-- one-time link sits in the address's inbox; it binds only when that link is
-- opened in the browser that started the sign-in, which is why the row keeps
-- TWO hashed secrets (the emailed token and a nonce cookie).
--
-- BOTH TABLES ARE REQUIRED AT BOOT while auth.providers.google or .microsoft
-- is on (module requiredTableKeys, registered in src/lib/db/index.ts), so
-- this migration is not optional for the cutover: the site refuses to start
-- without them rather than fall back to trusting the email.
--
-- THEY SHIP EMPTY AND MUST STAY THAT WAY. A row here is an assertion that a
-- named person's mailbox was proved; seeding one would hand a provider
-- account an address it never proved. Rows are written only by the module's
-- gate (packages/aicompany/src/auth/oauth-identity.ts) during a sign-in.
--
-- EVERY EXISTING GOOGLE/MICROSOFT SESSION DIES AT CUTOVER, by design: the
-- module's verifySessionToken now refuses a google/microsoft cookie carrying
-- no emailProof claim, and only the new gate mints that claim. Everyone
-- signed in through an OAuth door signs in once more; magic-link sessions are
-- untouched. Nothing in this file causes that - it is recorded here because
-- this is the migration that lands with it.
--
-- Generated by `drizzle-kit generate --name oauth_identities` against 0057's
-- snapshot (verified: 0058.prevId equals 0057.id, and the snapshot adds these
-- two tables and changes nothing else). IF NOT EXISTS hand-added per the
-- 0044-onward convention, so a hand-applied catch-up on the VM can run this
-- file again without failing the deploy's db:migrate step.
CREATE TABLE IF NOT EXISTS "oauth_confirmations" (
	"id" serial PRIMARY KEY NOT NULL,
	"provider" text NOT NULL,
	"subject" text NOT NULL,
	"email" text NOT NULL,
	"display_name" text,
	"token_hash" text NOT NULL,
	"browser_hash" text NOT NULL,
	"redirect" text,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "oauth_confirmations_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "oauth_identities" (
	"id" serial PRIMARY KEY NOT NULL,
	"provider" text NOT NULL,
	"subject" text NOT NULL,
	"email" text NOT NULL,
	"verified_via" text NOT NULL,
	"verified_at" timestamp with time zone NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "oauth_identities_provider_subject_email_key" UNIQUE("provider","subject","email")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "oauth_identities_email_idx" ON "oauth_identities" USING btree ("email");
