-- BRIEF INTAKE (§5.17.17, 2026-10-08). Three columns on rfp_documents:
-- intake_form ("rfp" | "brief"), written by runDocumentRead in the same
-- update that stamps "extracted": "brief" when the read found no section
-- structure and src/lib/rfp/brief.ts applyBriefMode put XL.net's standard
-- outline (src/lib/rfp/outline.ts) in its place, so the generate route
-- hands the drafter and the letter the whole text as the author's brief.
-- contact_name / contact_title: who the proposal is addressed to, grounded
-- verbatim against the read's fenced text (brief.ts groundContact) and
-- screened for injection; NULL when nothing grounded. resolve-draft.ts puts
-- them in the letter's addressee and salutation.
-- Every pre-round row reads "rfp" with no contact, which is exactly how it
-- was drafted.
--
-- This header was edited after the file was generated. Safe: drizzle's
-- migrator applies a file only when its journal `when` exceeds the last
-- __drizzle_migrations.created_at, and records the file's sha256 on apply
-- without ever comparing it afterwards; the statements below are unchanged
-- apart from IF NOT EXISTS.
--
-- Generated by `drizzle-kit generate --name rfp_brief_intake` against
-- 0059's snapshot (verified: 0060.prevId equals 0059.id, and the snapshot
-- adds these three columns and changes nothing else); IF NOT EXISTS
-- hand-added per the 0044-onward convention, so a hand-applied catch-up on
-- the VM can run this file again without failing the deploy's db:migrate
-- step.
ALTER TABLE "rfp_documents" ADD COLUMN IF NOT EXISTS "intake_form" text DEFAULT 'rfp' NOT NULL;--> statement-breakpoint
ALTER TABLE "rfp_documents" ADD COLUMN IF NOT EXISTS "contact_name" text;--> statement-breakpoint
ALTER TABLE "rfp_documents" ADD COLUMN IF NOT EXISTS "contact_title" text;
